create table
  public.ml_ledger_entries (
    id bigint generated by default as identity,
    transaction_id integer not null,
    color text not null,
    change integer not null,
    constraint ml_ledger_entries_pkey primary key (id)
  ) tablespace pg_default;
