create table
  public.potions (
    id bigint generated by default as identity,
    item_sku text not null,
    item_price integer not null,
    item_name text not null,
    potion_type integer[] not null,
    constraint potions_pkey primary key (id)
  ) tablespace pg_default;
