create table
  public.potions_ledger_entries (
    id integer generated by default as identity,
    transaction_id integer not null,
    potion_type integer[] not null,
    change integer not null,
    constraint potions_ledger_entries_pkey primary key (id)
  ) tablespace pg_default;
