create table
  public.gold_ledger_entries (
    id integer generated by default as identity,
    transaction_id integer not null,
    change integer not null default 0,
    constraint transactions_pkey primary key (id)
  ) tablespace pg_default;
